### PR TITLE
use async await instead of using the callback

### PR DESCRIPTION
**Pull request by hosseinmd**
in the es6 we can use async await.
in this commit we can use that.

please pull this commit and change version number

### CODE REVIEW

**Comment by hosseinmd** [comment]
my pleasure.

**Comment by pusherman** [comment]
Thanks for this work!  I will get it merged in, just not sure what version it will make it in to since it will have a pretty big impact on developers once they upgrade.

**Comment by hosseinmd** [comment]
my pleasure.
I think the best choice for this module might be 5.0.0.
Because a fundamental change occurred in the module

**Comment by hosseinmd** [comment]
please pull it

**Comment by pusherman** [comment]
There are a good amount of spacing and code formatting issues.  Can you clean those up?

**Comment by hosseinmd** [comment]
Sorry for the delay
The change is done

**Comment by pusherman** [comment]
Thanks for cleaning up the formatting! The only thing left is returning NULL on an error. Can we just return the error description instead so the user has a little more info about why it failed?

**Comment by hosseinmd** [comment]
it's right. but user don't want do work more.
we can print the errors description in log. do you want i do that?

**Comment by pusherman** [comment]
We can leave it as is for now and do more investigating later.  Thanks again!

**Comment by hosseinmd** [comment]
thanks.
How many days ago I became unemployed.
I am writing english but not very well. because my native language is Azeri
but i learned Persian.
I would love to challenge myself with big projects.I can work remotely or
at work.
Can you help me?

Regards,
Hossein Mohammadi

**Comment by pusherman** [comment]
Unfortunately I can not help at this time.  If something comes up though, I'll let you know.

**Pull request merged**
