### PR TITLE
[FEATURE] getWIFIIPV4Address

### PR DESCRIPTION
**Pull request by Rapsssito**
Get the device's WiFi interface IP address, if it is connected.

### CODE REVIEW

**Comment by pusherman** [comment]
Thanks for this.  I believe it's nice to have-- I would just like for it to be consistent on the iOS side.  Do you know if iOS has the same problem this is resolving?  If yes, maybe we make this the default and create another method for getting all the IPs of any interfaces?

**Comment by Rapsssito** [comment]
I don't know if iOS has the same problem. However, looking through the code, I saw that the method follows almost the same structure as the Android version (I could be wrong, I don't know much about Objective-C).
In `ios/RNNetworkInfo.m` in line 172: `NSArray *searchArray = @[ IOS_WIFI @"/" IP_ADDR_IPv4, IOS_CELLULAR @"/" IP_ADDR_IPv4 ];`, looks like it iterates through the interfaces WiFi **first** and Cellular **second**, so it will probably have the same problem described in issue #72.

For the **getWIFIIPV4Address()** in iOS, I just copied getIPV4Address() from `ios/RNNetworkInfo.m` and changed the following line:

`+ Line 197: NSArray *searchArray = @[ IOS_WIFI @"/" IP_ADDR_IPv4 ];`

So in getWIFIIPV4Address() it should only look for the device's WiFi interface.

**Comment by pusherman** [comment]
Oh, sorry, I was looking at the PR on my phone and overlooked you had implemented it in iOS as well.  Great!

Let me think about the API a little.  I don't love having both `getWIFIIPV4Address` and `getIPV4Address` but you're right, this is a nice method to have.

**Comment by Rapsssito** [comment]
A possibility is to have different methods for WiFi, Cellular and Ethernet (?). However, it might be a better idea to have a `getIPV4Address` with a parameter to select which interface you want to look for (defaulting on WiFi, because I think that would be the most common use).

**Comment by richardtks** [comment]
> A possibility is to have different methods for WiFi, Cellular and Ethernet (?). However, it might be a better idea to have a `getIPV4Address` with a parameter to select which interface you want to look for (maybe defaulting on WiFi, because I think that would be the most common use).

I am totally agree with this approach, as we might need to get the ip address for wifi or cellular.

**Comment by pusherman** [comment]
> A possibility is to have different methods for WiFi, Cellular and Ethernet (?). However, it might be a better idea to have a `getIPV4Address` with a parameter to select which interface you want to look for (maybe defaulting on WiFi, because I think that would be the most common use case).

What about, for now, if we change it so the `getIPV4Address` method will return the wifi IP first, if it exists.  Otherwise, it will return the cellular IP?  I agree that getting the local wifi address is the most common use case.

I think a bigger, but nicer, future change we could just have one method `getIPAddress` and it would return a hash of all IPs with details about each (wifi, cellular, loopback, etc).

**Comment by Rapsssito** [comment]
> What about, for now, if we change it so the `getIPV4Address `method will return the wifi IP first, if it exists. Otherwise, it will return the cellular IP? I agree that getting the local wifi address is the most common use case.

I adapted the code. Checking if the WiFi address exists is done in JavaScript. However, I don't know TypeScript, so I don't know if the file `NetworkInfo.d.ts` needs to be changed too.

**Comment by pusherman** [comment]
> I adapted the code. Checking if the WiFi address exists is done in JavaScript. However, I don't know TypeScript, so I don't know if the file NetworkInfo.d.ts needs to be changed too.

No, that should still be fine.  Thanks for making those changes!  I made one quick code formatting change.  I'm traveling so I don't have access to my Android device to test on.  Can you give it one last test using my latest changes?  If it's okay, I think we are good to merge this one.

Thanks for your help!

**Comment by Rapsssito** [comment]
I have tested it on my Android device, Google Pixel 3. This is what I am getting:

**WiFi & Cellular enabled**: `'192.168.1.xx'`
**WiFi enabled**: `'192.168.1.xx'`
**Cellular enabled**: `'10.xx.xx.xx.xx'`
**None**: `'0.0.0.0'`

**Pull request merged**
