### PR TITLE
Check SupplicantState Of WifiInfo

### PR DESCRIPTION
**Pull request by yosimasu**
When I turn off Wifi on Android, the following situation happen:
1. getSSID() return `<unknown ssid>`
2. getBSSID() return `00:00:00:00:00:00`

I found solution from stackoverflow:
https://stackoverflow.com/a/34848930/5732760

### CODE REVIEW

**Comment by yosimasu** [comment]
@pusherman Please review my pr.

**Comment by pusherman** [comment]
@yosimasu - i'm out of town for work, i've reviewed the code but want to reproduce the error you are trying to solve.  I will merge when I return home and can reproduce.

**Comment by yosimasu** [comment]
@pusherman, 

I test on Sony Xperia Performance, 
which android version is 7.1.1

**Comment by pusherman** [comment]
@yosimasu - so sorry for the delay!  I've finally had a chance to test this out.  So your fix prevents the "Unknown SSID" string from coming back when the wifi is turned off.  Are you wanting to do this to know when the wifi is off vs being on cellular where we do not have an SSID?

**Comment by yosimasu** [comment]
@pusherman 

Yes. That's what I want.
On iOS device I try, it throws `error` not `unknown ssid`.
I think it should have the same behaviour on React Native JavaScript Layer.

**Comment by yosimasu** [comment]
@pusherman 

I aligned the error value on Android.

**Comment by yosimasu** [comment]
@pusherman 

I also fix v2.2.0, but I can not give a pr to v2.2.0.

**Comment by vlkosinov** [comment]
@pusherman ping

**Comment by pusherman** [comment]
@yosimasu - so sorry but I completely forgot about this PR.  It now has merge conflicts but if you can get those resolved I will get this merged in ASAP.

**Comment by yosimasu** [comment]
@pusherman 

I have merged the differences.
Please check it.

**Comment by pusherman** [comment]
looks good, thanks @yosimasu!

**Pull request merged**
